### ISSUE TITLE
Cache database calls

### ISSUE THREAD

**Issue by UnsignedArduino** [AakashSharma7269/erin#15]
> Optimizations:
> - The current system is extremely heavy, it makes excessive database calls. we'll need to write a global wrapper for all the database connections. The main goal for this is to deal with the prefix issue, as of now the bot makes a database call for 'every' message sent on discord
>
> Example code:
> ```python3
> from utils.prefix import PrefixManager
> 
> PrefixManager.getprefix(ctx.message.guild)
> ```

**Comment by UnsignedArduino** [comment]
Note to self/anyone working on this: when you make the cache, make sure you clear it when the associated database values are changed. Foe example, if a server owner changes the prefixes, we should clear the cache for the prefixes for that server. (This may involve writing a custom cache command cause I don't see a way to clear a specific value from the cache for `functools.lru_cache` and `cache`...

**Comment by UnsignedArduino** [comment]
(Opened draft PR https://github.com/AakashSharma7269/erin/pull/16 which eventually should fix this issue)

**Comment by Shinyzenith** [comment]
https://stackoverflow.com/questions/37653784/how-do-i-use-cache-clear-on-python-functools-lru-cache

**Comment by Shinyzenith** [comment]
@UnsignedArduino I'm gonna be writing a util class for the prefix 😄 you can write your own implementation and push to the rewrite repo. 👋🏽

**Comment by Shinyzenith** [comment]
I'm closing this for now.
