### ISSUE TITLE
More ways of accessing the prefix

### ISSUE THREAD

**Issue by UnsignedArduino** [AakashSharma7269/erin#7]
Instead of having to do `@Erin. prefix` we could also have `@Erin. prefixes` and even just `@Erin.`. If we try to do something else like `@Erin. help` then the bot should say something like `Please use the available prefixes: <list of prefixes>`.We can also have `-prefix` list them all and also tell the user to specify `add` or `remove` to change the list. And maybe have `-prefixes` do the same as `-prefix`. 

If ya like this idea I can try to implement this via a PR.

**Comment by Shinyzenith** [comment]
Previously users could type `@Erin` to get the prefix list but it got annoying very quickly when users just wanted to mention the bot without getting the prefix list, hence the `@Erin prefix` system was implemented. I can add `@Erin prefixes` too. 

About the `-prefix` and `-prefixes` i personally don't feel that's a good idea so i won't be implementing that. `@Erin help` This can be implemented but i'm not sure how, i know it can be done but i don't think it works when the bot is listening to an array of prefixes (mongo returns an array of string prefixes which are passed to the client object)... If you can submit a PR for `@Erin help` for now then that would be good.

**Comment by UnsignedArduino** [comment]
So when I run `@Erin. help` it should show the help or tell the user to use the prefixes?

**Comment by UnsignedArduino** [comment]
Either way, I can just copy and paste the code that prints the prefix when you do `@Erin. prefix` and change the message and the command the bot is listening to.

**Comment by Shinyzenith** [comment]
> So when I run `@Erin. help` it should show the help or tell the user to use the prefixes?

`@Erin <commandname>` could be any command, would be nice if that would get executed

if this is out of your skill set then implement the prefix idea you're talking about (idk how to get this done cuz as i said i think arrays disable the ping functionality)

**Comment by Shinyzenith** [comment]
> Either way, I can just copy and paste the code that prints the prefix when you do `@Erin. prefix` and change the message and the command the bot is listening to.

Well, do what you must. That's all i'll say, this is an open source project sooooo it's pretty much whatever you want to make it unless someone comes up with a better / more efficient idea 😎 


I'm closing this for now, submit the PR when you're free or ping me on discord if you don't have time
