### ISSUE TITLE
Fix grammar in cooldown message

### ISSUE THREAD

**Issue by UnsignedArduino** [AakashSharma7269/erin#8]
![image](https://user-images.githubusercontent.com/38868705/124668901-88aa3100-de7f-11eb-8432-3be886e62953.png)
Should either fix it to something like `You must wait <time> second(s) to use this command again!` or properly add and remove the "s".

**Comment by actualdankcoder** [comment]
Fixed in 9dee87abfba1832600ccd49f37f6520ce809d380

**Comment by actualdankcoder** [comment]
wow I made a typo in "grammar"

> Fixed in [9dee87a](https://github.com/AakashSharma7269/erin/commit/9dee87abfba1832600ccd49f37f6520ce809d380)
